Add developer role to user card and permissions
LastArtistStanding/last-artist-standing pull request #161
Opened 2021-06-30 05:11 UTC by jamestmartin

* Adds an `is_developer` column to the `users` table.
* Makes the user card of developers green (an arbitrary green with the same saturation and brightness as moderators. pic related; feel free to bikeshed).
* Adds two new permissions (e.g. for a development updates board): `4` for just admins and developers, and `5` for admins, moderators, or developers.

![developer user card](https://user-images.githubusercontent.com/25411849/123904762-e261a700-d925-11eb-945a-d2b0ba2c2cc7.png)

I'd prefer if it were more clear to users that developers do not have moderator permissions. Also, as one of the least consistent, lowest-skill members of the site I don't necessarily need the extra attention. Not saying that I *don't* want to have it either, but I'm kinda on the fence about it.

2021-06-30 05:16 UTC, jamestmartin commented
btw if you approve this commit, please let me merge it myself. GitHub's stupid stuff like merge commits and "committed by" drive me nuts. They used to let you merge stuff the normal way through the web interface, but now you have to pull it and re-push it yourself or it'll generate extra garbage.

2021-07-07 02:29 UTC, the1banana requested changes

2021-07-07 02:29 UTC, the1banana commented on app/models/user.rb
> +  end
Hm. While I do acknowledge that this is probably dated and will probably revised in the future for a more robust, database-focused solution to role management, I do also think that some sanity with regards to the numbers vaguely being characterized as relative to a hierarchy would be suitable (minor, but it does help avoid console-admin mistakes).
To that end:
1: everybody (no check)
2: is_dev || is_mod || is_admin
3: is_dev || is_admin
4: is_mod || is_admin
5: is_admin

**Note: you will need to add a migration that converts the existing permission levels into their equivalent ones in this new hierarchy.**

2021-08-23 03:53 UTC, jamestmartin commented
The low bit is admins. The second bit is mods. The third bit is devs. No bits is no-one. All bits is everyone.

Thus, the permission level cheat sheet:
`-1` (all ones): everyone
`0` (`0b000`): no-one
`1` (`0b001`): admins
`2` (`0b010`): mods
`3` (`0b011`): mods and admins
`4` (`0b100`): devs
`5` (`0b101`): devs and admins
`6` (`0b110`): devs and mods
`7` (`0b111`): devs, mods, and admins

A greater number means more people have clearance.

2021-08-23 23:43 UTC, merged